databases:
  - name: accounting-db
    plan: free
    region: frankfurt
    databaseName: accounting
    user: frederik

services:
  - type: web
    plan: free
    region: frankfurt
    name: accounting-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: accounting-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.10.6